[TF-Grid_Block]
embedding = 32
kernel_size = 4
stride = 1
hidden_size = 100
width = 255

[FSM]
channels = 4
num_heads = 4

[Phase_Encoder]
channels = 4
kernel_size = [3, 1]
stride = [1, 1]
padding = [1, 0]

[DL_TF-Grid]
num_blocks = 5
kernel_size = [3, 3]
stride = [1, 1]
padding = [1, 0]

[PL_TF-Grid]
num_blocks = 5
num_middles = 4

[FFT]
n_fft = 512
hop_length = 256
win_length = 512



